# 1 Prepare Work

In [6]:
import numpy as np
import os.path
import jieba
import pandas as pd
import re

In [7]:
csv_path = r'D:\Assignment\Project_01\newsdata.csv'
if not os.path.isfile(csv_path):
    print('Input error, please enter correct path!')
else:
    print('Success!')

Success!


In [8]:
ori_news_csv = pd.read_csv(csv_path, encoding='ansi', error_bad_lines=False, usecols=[0, 2, 3])

D:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3049: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [9]:
ori_news_csv.head()

id                  source  \
0  89617  快科技@http://www.kkj.cn/   
1  89616  快科技@http://www.kkj.cn/   
2  89615  快科技@http://www.kkj.cn/   
3  89614                     新华社   
4  89613                   深圳大件事   

                                             content  
0  此外，自本周（6月12日）起，除小米手机6等15款机型外，其余机型已暂停更新发布（含开发版/...  
1  骁龙835作为唯一通过Windows 10桌面平台认证的ARM处理器，高通强调，不会因为只考...  
2  此前的一加3T搭载的是3400mAh电池，DashCharge快充规格为5V/4A。\n至于...  
3      这是6月18日在葡萄牙中部大佩德罗冈地区拍摄的被森林大火烧毁的汽车。新华社记者张立云摄\n  
4  （原标题：44岁女子跑深圳约会网友被拒，暴雨中裸身奔走……）\n@深圳交警微博称：昨日清晨交...

In [10]:
ori_news_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90532 entries, 0 to 90531
Data columns (total 3 columns):
id         90532 non-null object
source     89720 non-null object
content    87165 non-null object
dtypes: object(3)
memory usage: 2.1+ MB


In [11]:
ori_news_csv.describe()

id source content
count           90532  89720   87165
unique          90428   1049   74995
top     ,{"type":"新闻"    新华社    \n\n
freq               32  78661     177

In [12]:
news_csv = ori_news_csv.dropna(axis=0)

In [13]:
news_csv.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 87163 entries, 0 to 90531
Data columns (total 3 columns):
id         87163 non-null object
source     87163 non-null object
content    87163 non-null object
dtypes: object(3)
memory usage: 2.7+ MB


In [14]:
news_csv[news_csv['source'].str.contains('新华')]

id source                                            content
3      89614    新华社      这是6月18日在葡萄牙中部大佩德罗冈地区拍摄的被森林大火烧毁的汽车。新华社记者张立云摄\n
19     89600    新华网  国歌法草案首次提请最高立法机关审议\n点击图片进入下一页\n新闻：十二届全国人大常委会第二十...
27     89592    新华网  当地时间2017年6月17日，土耳其马尼萨省，在土耳其第1步兵训练大队司令部军营，590名土...
29     89590    新华网  英国与欧盟的“脱欧”谈判于19日正式开始。然而此时，英国首相特雷莎·梅正面临着空前的政治压力...
41     89578    新华社      这是6月18日在葡萄牙中部大佩德罗冈地区拍摄的被森林大火烧毁的汽车。新华社记者张立云摄\n
53     89566    新华网  戈壁的大漠黄沙曾掩埋了无数西域古道，而如今一条大漠天路正顽强地与黄沙“搏斗”，在乌兰布和、腾...
67     89552   新华社@  从百度、支付宝到App?“高考志愿填报”五花八门\n顾女士近来减少了刷朋友圈的频率，一有时间...
97     89522    新华社  新华社韩国济州6月18日电综述：亚投行第二届年会三大亮点\n新华社记者 耿学鹏 严蕾\n亚洲...
106    89513    新华网  粤港澳概念板块午后走强，珠海港、恒基达鑫、白云机场等个股的午后纷纷快速拉升。\n据悉，首届粤...
115    89504    新华社  新华社北京6月18日电 经军委领导批准，《军营理论热点怎么看·2017》日前印发全军。\n为...
242    89386    新华网  东方卫视明星旅游体验综艺节目《旅途的花样》6月17日（周六）晚播出了第三期节目。本周，“花样...
316    89312    新华社  新华社兰州6月19日电（记者张钦）记者19日了解到，刚刚出台的《甘肃省网络扶贫行动的实施方案...
323    89305    新华社  新华社乌鲁木齐6月18日电（记者杜刚、王秉阳）6月18日，新疆天山天池首次举办山地马拉松比赛...
325    89303    新华社  新华社北京6月19日电（记者熊丰）记者从公安部消防局获悉，19日上午6时，由公安部消防局组织...
340    89288    新华网  新华社北京６月２３日电（记者邢静）幸福是人们对生活最美好的期待，２０１７年哪些城市生活更幸福...
341    89287    新华网  新华社昆明6月23日电（记者王研）近年来，随着云南航空业的迅速发展，机场禁毒形势也日益严峻。...
342    89286    新华网  新华社北京６月２３日电（记者倪元锦）２１日起，京津冀迎来今年以来最强降雨。记者采访气象专家，...
346    89282    新华网  新华社北京６月２３日电（记者 倪元锦）２１日起，京津冀迎来今年以来最强降雨。记者采访气象专家...
376    89252    新华网  新华社哈尔滨6月23日电（记者 许正）记者23日从黑龙江省环保厅获悉，这个省目前建立的自然保...
391    89241    新华网  新华社合肥６月２３日电? 题：安徽不断将跨省流域补偿试点推向深入\n新华社记者杨丁淼\n当罗...
403    89229    新华网  新华社重庆６月２３日电? 题：“悟空”为何跌下共享风口？——重庆首家共享单车“退市”观察\n...
460    89172    新华网  新华社贵阳６月２３日电（记者 李黔渝）贵州省政府近日下发通知，对严重影响公共安全的中学、医院...
461    89171    新华网  新华社广州6月23日电 题：激发内生动力 走在脱贫路上——广东探索东西部扶贫协作新路径\n新...
463    89169    新华网  新华社南京6月23日电（记者 朱国亮）23日在常州召开的江苏首届VR/AR（虚拟现实/增强现...
531    89106    新华网  于2010年12月14日正式于杭州成立、由裕隆集团与东风汽车集团所建立的合资企业东风裕隆汽车...
534    89103    新华网  美国《华盛顿邮报》6月14日披露，主持“通俄门”调查的特别检察官罗伯特·米勒正在调查总统唐纳...
577    89076  新华通讯社  刘国梁\n??新华社北京6月20日电记者从中国乒乓球协会获悉，国家乒乓球队管理模式将进行改革...
579    89074    新华社  　　暑期旅游旺季是各大旅游景区开门迎客的好时机。然而，有5家5A级景区却高兴不起来：国家旅游...
581    89072    新华社  　　新华社北京6月20日电　总部设在德国波恩的国际残奥委会在当地时间19日宣布，中国残联主席...
592    89065    新华网  新华社成都6月23日电（记者周相吉）四川省在坚决查处违纪违法的同时，又为“改革创新、担当有为...
...      ...    ...                                                ...
90502     30    新华社  新华社照片，外代，2017年6月7日\n（外代二线）足球——世预赛：葡萄牙备战\n6月6日，...
90503     29    新华社  新华社照片，外代，2017年6月7日\n（外代二线）足球——世预赛：葡萄牙备战\n6月6日，...
90504     28    新华社  新华社照片，外代，2017年6月7日\n（外代二线）足球——世预赛：葡萄牙备战\n6月6日，...
90505     27    新华社  新华社照片，外代，2017年6月7日\n（外代二线）足球——世预赛：葡萄牙备战\n6月6日，...
90506     26    新华社  新华社照片，外代，2017年6月7日\n（外代二线）足球——世预赛：葡萄牙备战\n6月6日，...
90507     25    新华社  新华社照片，外代，2017年6月7日\n（外代二线）足球——世预赛：葡萄牙备战\n6月6日，...
90508     24    新华社  新华社照片，外代，2017年6月7日\n（外代二线）蚕丝生产\n6月6日，在印度特里普拉邦特...
90509     23    新华社  新华社照片，外代，2017年6月7日\n（外代二线）蚕丝生产\n6月6日，在印度特里普拉邦特...
90510     22    新华社  新华社照片，外代，2017年6月7日\n（外代二线）蚕丝生产\n5月30日，在印度特里普拉邦...
90511     21    新华社  新华社照片，外代，2017年6月7日\n（外代二线）蚕丝生产\n6月6日，在印度特里普拉邦特...
90512     20    新华社  新华社照片，外代，2017年6月7日\n（外代二线）蚕丝生产\n5月30日，在印度特里普拉邦...
90513     19    新华社  \n\n2017年4月27日，在首尔光化门广场，民众在集会上手举反“萨德”标语。（新华社记者...
90514     18    新华社  \n新华社巴格达6月6日电（记者魏玉栋　程帅朋）伊拉克西部安巴尔省一处市场6日晚发生自杀式爆...
90515     17    新华社  新华社照片，外代，2017年6月7日\n（外代二线）足球——国际友谊赛：德国平丹麦\n6月6...
90516     16    新华社  新华社照片，外代，2017年6月7日\n（外代二线）足球——国际友谊赛：德国平丹麦\n6月6...
90517     15    新华社  新华社照片，外代，2017年6月7日\n（外代二线）足球——国际友谊赛：德国平丹麦\n6月6...
90518     14    新华社  新华社照片，外代，2017年6月7日\n（外代二线）足球——国际友谊赛：德国平丹麦\n6月6...
90519     13    新华社  新华社照片，外代，2017年6月7日\n（外代二线）足球——国际友谊赛：德国平丹麦\n6月6...
90520     12    新华社  新华社照片，外代，2017年6月7日\n（外代二线）足球——国际友谊赛：德国平丹麦\n6月6...
90521     11    新华社  新华社照片，外代，2017年6月7日\n（外代二线）足球——国际友谊赛：德国平丹麦\n6月6...
90522     10    新华社  新华社照片，外代，2017年6月7日\n（外代二线）足球——国际友谊赛：德国平丹麦\n6月6...
90523      9    新华社  新华社照片，外代，2017年6月7日\n（外代二线）足球——国际友谊赛：德国平丹麦\n6月6...
90524      8    新华社  新华社照片，北京，2017年6月7日\n电影《血战湘江》举行清华大学巡映活动\n6月6日，电...
90525      7    新华社  新华社照片，北京，2017年6月7日\n电影《血战湘江》举行清华大学巡映活动\n6月6日，清...
90526      6    新华社  新华社照片，北京，2017

In [15]:
news_csv['is_xinhua'] = np.where(news_csv['source'].str.contains('新华'), 1, 0)

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [16]:
news_csv.head()

id                  source  \
0  89617  快科技@http://www.kkj.cn/   
1  89616  快科技@http://www.kkj.cn/   
2  89615  快科技@http://www.kkj.cn/   
3  89614                     新华社   
4  89613                   深圳大件事   

                                             content  is_xinhua  
0  此外，自本周（6月12日）起，除小米手机6等15款机型外，其余机型已暂停更新发布（含开发版/...          0  
1  骁龙835作为唯一通过Windows 10桌面平台认证的ARM处理器，高通强调，不会因为只考...          0  
2  此前的一加3T搭载的是3400mAh电池，DashCharge快充规格为5V/4A。\n至于...          0  
3      这是6月18日在葡萄牙中部大佩德罗冈地区拍摄的被森林大火烧毁的汽车。新华社记者张立云摄\n          1  
4  （原标题：44岁女子跑深圳约会网友被拒，暴雨中裸身奔走……）\n@深圳交警微博称：昨日清晨交...          0

## 2 Process Data

## 2.1 Get 1000 samples of '新华社' and 1000 samples of '非新华社' 

In [55]:
X = []
Y = []
i = 0
j = 0

In [56]:
content_list = news_csv['content'].tolist()
for k, boolean in enumerate(news_csv['is_xinhua']):
    if boolean == 1 and i < 100:
        X.append(content_list[k])
        Y.append(1)
        i += 1
    elif boolean == 0 and j < 100:
        X.append(content_list[k])
        Y.append(0)
        j += 1
    elif i >= 200 and j >= 200:
        break

In [57]:
len(X)

200

In [58]:
len(Y)

200

## 2.2 Cut the samples

In [59]:
def token(string):
    return ''.join(re.findall(r'[\w|\d]+', string))
def cut(string):
    return jieba.lcut(string)

In [60]:
cut_X = []

In [61]:
label = ['新华', '新华社', '新华网']
for news in X:
    tmp = cut(token(news))
    for word in tmp:
        if word in label:
            tmp.remove(word)
    cut_X.append(tmp)

In [62]:
len(cut_X)

200

In [63]:
cut_X[3]

['这是',
 '6',
 '月',
 '18',
 '日',
 '在',
 '葡萄牙',
 '中部',
 '大',
 '佩德罗',
 '冈',
 '地区',
 '拍摄',
 '的',
 '被',
 '森林',
 '大火',
 '烧毁',
 '的',
 '汽车',
 '记者',
 '张立',
 '云摄']

# 3 Embdding

## 3.1 Get the probability

In [31]:
import gensim

D:\Anaconda3\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [32]:
def memo(func):
    cache = {}

    def _wrap(*args): ## ? *args, **kwargs
        if args in cache: result = cache[args]
        else:
            result = func(*args)
            cache[args] = result
        return result
    return _wrap

In [33]:
@memo
def get_probability(word, model):
    keys = model.vocab.keys()
    total_words_count = sum([v.count for k, v in model.vocab.items()])
    esp = 1 / total_words_count

    if word in keys:
        word_count = model.vocab[word].count
        return word_count / total_words_count
    else:
        return esp

In [34]:
Word2vec_model_path = r'D:\Assignment\Assignment_08\X_Word2Vec_model\X_Word2vec_model.w2v'

In [35]:
word2vec = gensim.models.word2vec.Word2Vec.load(Word2vec_model_path).wv

In [36]:
get_probability('啊', word2vec)

4.5954059429572944e-05

## 3.2 Get the SIF sentence embdding

In [37]:
from sklearn.decomposition import PCA

In [38]:
@memo
def get_SIF(word, model, a=0.01):
    return (a + get_probability(word, model))

In [53]:
def SIF_sentence_embdding(sentence, model, a=0.01):
    result = 0
    i = 0
    for word in sentence:
        temp = model[word] * get_SIF(word, model)
        result += temp
    return result

In [40]:
def PCA_SIF_sentence_embdding(news, model=word2vec, embedding_size=50, a=0.01):
    X = [SIF_sentence_embdding(sentence, model) for sentence in news]
    
    pca = PCA(n_components=min(embedding_size, len(X)))
    
    pca.fit(np.array(X))
    
    u = pca.components_[0]  # the PCA vector
    u = np.multiply(u, np.transpose(u))  # u x uT
    
    # pad the vector?  (occurs if we have less sentences than embeddings_size)
    if len(u) < embedding_size:
        for i in range(embedding_size - len(u)):
            u = np.append(u, 0)  # add needed extension for multiplication below
    # resulting sentence vectors, vs = vs -u x uT x vs
    Y = []
    for Vs in X:
        sub = np.multiply(u, Vs)
        Y.append(np.subtract(Vs, sub))
    return Y

In [64]:
len(cut_X)

200

In [65]:
X = PCA_SIF_sentence_embdding(cut_X)

In [66]:
X[0]

array([-0.3388332 ,  0.31367433, -1.1886572 , -0.19834372, -0.76355356,
        0.78088987, -0.12510942, -0.04191329, -1.1362219 ,  1.3453871 ,
        0.70736414, -0.02386289,  0.23305674, -0.08110896, -0.06191227,
       -0.42825627,  0.86159015,  0.03354946,  0.45374542, -0.72452825,
       -0.42216712,  0.06371682, -0.04275539,  1.0201747 , -0.70221204,
       -0.40013233, -0.20592153,  0.8326778 , -0.19719183, -0.84711224,
        0.4768416 ,  0.13187121, -0.00883853, -0.48734808, -0.6989546 ,
       -0.74409974, -0.35922697, -0.17189074,  0.40694484,  0.9456374 ,
        0.24614866,  0.19374016,  0.7415607 ,  0.8048215 ,  0.16519848,
       -0.18348104,  0.33834675, -0.10276471,  0.53404146,  0.50047386],
      dtype=float32)

# 4 Get the train data and the test data

In [67]:
len(Y)

200

In [70]:
X = np.array(X)
Y = np.array(Y)

In [71]:
X.shape

(200, 50)

In [72]:
Y.shape

(200,)

In [73]:
from sklearn.model_selection import train_test_split

In [74]:
from sklearn.preprocessing import StandardScaler

In [75]:
from sklearn.metrics import accuracy_score

In [76]:
scaler = StandardScaler()

In [77]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [78]:
X_tr_arr = X_train
X_ts_arr = X_test

In [79]:
print('Input Shape', (X_tr_arr.shape))
print('Output Shape', X_test.shape)

Input Shape (160, 50)
Output Shape (40, 50)


In [80]:
print(y_train.shape)
print(y_test.shape)

(160,)
(40,)


In [81]:
y_tr_arr = y_train
y_ts_arr = y_test

In [82]:
y_test

array([0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0])

# 5 Scikit-learn

In [89]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix
def get_performance(clf, X_, y_):
    y_hat = clf.predict(X_)
    print('percision is: {}'.format(precision_score(y_, y_hat)))
    print('recall is: {}'.format(recall_score(y_, y_hat)))
    print('roc_auc is: {}'.format(roc_auc_score(y_, y_hat)))
    print('confusion matrix: \n{}'.format(confusion_matrix(y_, y_hat, labels=[0, 1])))

## 5.1 Naive Bayes

In [90]:
from sklearn.naive_bayes import GaussianNB
clf = GaussianNB()
clf.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [91]:
get_performance(clf,X_train,y_train)
print('\n')
get_performance(clf,X_test,y_test)

percision is: 0.5714285714285714
recall is: 0.9
roc_auc is: 0.6125
confusion matrix: 
[[26 54]
 [ 8 72]]


percision is: 0.53125
recall is: 0.85
roc_auc is: 0.55
confusion matrix: 
[[ 5 15]
 [ 3 17]]


## 5.2 Decision Tree

In [93]:
from sklearn.tree import DecisionTreeClassifier
clf_tree = DecisionTreeClassifier(class_weight={0:1,1:1},criterion='entropy',max_features=50)
clf_tree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight={0: 1, 1: 1}, criterion='entropy',
            max_depth=None, max_features=50, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [94]:
get_performance(clf_tree,X_train,y_train)
print('\n')
get_performance(clf_tree,X_test,y_test)

percision is: 1.0
recall is: 1.0
roc_auc is: 1.0
confusion matrix: 
[[80  0]
 [ 0 80]]


percision is: 0.7142857142857143
recall is: 0.75
roc_auc is: 0.7249999999999999
confusion matrix: 
[[14  6]
 [ 5 15]]


## 5.3 SVM

In [97]:
from sklearn import svm
clf_svm = svm.SVC(gamma='scale')
clf_svm.fit(X_train,y_train) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [98]:
get_performance(clf_svm,X_train,y_train)
print('\n')
get_performance(clf_svm,X_test,y_test)

percision is: 0.8192771084337349
recall is: 0.85
roc_auc is: 0.83125
confusion matrix: 
[[65 15]
 [12 68]]


percision is: 0.7
recall is: 0.7
roc_auc is: 0.7
confusion matrix: 
[[14  6]
 [ 6 14]]


## 5.4 Random Forset

In [99]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
clf_RF = RandomForestClassifier(n_estimators=10, max_depth=5,random_state=0)
clf_RF.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=5, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [100]:
get_performance(clf_RF,X_train,y_train)
print('\n')
get_performance(clf_RF,X_test,y_test)

percision is: 1.0
recall is: 0.925
roc_auc is: 0.9625
confusion matrix: 
[[80  0]
 [ 6 74]]


percision is: 0.7368421052631579
recall is: 0.7
roc_auc is: 0.725
confusion matrix: 
[[15  5]
 [ 6 14]]


## 5.5 KNN

In [103]:
from sklearn.neighbors import KNeighborsClassifier
clf_knn = KNeighborsClassifier(n_neighbors=5)
clf_knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [104]:
get_performance(clf_knn,X_train,y_train)
print('\n')
get_performance(clf_knn,X_test,y_test)

percision is: 0.8701298701298701
recall is: 0.8375
roc_auc is: 0.85625
confusion matrix: 
[[70 10]
 [13 67]]


percision is: 0.7857142857142857
recall is: 0.55
roc_auc is: 0.7
confusion matrix: 
[[17  3]
 [ 9 11]]
